server.port=8085
spring.application.name=backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Cloudinary credentials
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

jwt.secret=${JWT_SECRET}
#JWT expiration in milliseconds, keep lower for more security.
jwt.expiration=${JWT_EXPIRATION}

app.frontend.url=${FRONTEND_URL}

# auto-create tables from entities
spring.jpa.hibernate.ddl-auto=update

#Set tomcat maximum upload limit
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
