spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/matchme
spring.datasource.username=postgres
spring.datasource.password=1234561
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# auto-create tables from entities
spring.jpa.hibernate.ddl-auto=update

jwt.secret=super-secure-random-secret-key-123456
jwt.expiration=3600000